[package]
name = "pneumatic_data"
version = "0.1.0"
edition = "2021"

[dependencies]
pneumatic_core = { git = "https://github.com/garrettkolson/pneumatic_core.git" }
rocksdb = "0.23.0"
once_cell = "1.19.0"
